name: Pull code, rebuild files and restart pm2 processes

on:
  push:
    branches: [main]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Rebuild Server with latest from Main
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd postitt.io/Back-end
            git pull
            npm install
            npx tsc
            pm2 restart server
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
